name: phpunit

on: [push]

env:
  XDEBUG_MODE: coverage

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer Installs
        uses: php-actions/composer@v6
        with:
          dev: yes

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6.19
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          memory_limit: 512M
