name: phpunit

on: [push]

env:
  XDEBUG_MODE: coverage
  PHP_VERSION: 8.2

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v6

      - name: Run Composer
        run: |
          docker run --rm --interactive --volume $GITHUB_WORKSPACE:/app composer/composer dump-autoload

      - name: Check BIN
        run: |
          ls ./vendor/bin
      
      - name: Run PHPUnit
        run: |
          docker run --rm --interactive --volume $PWD:/app -w /app php:8.2-cli php ./vendor/bin/phpunit
          
