name: phpunit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer Installs
        uses: php-actions/composer@v6
        with:
          dev: yes

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3.0.3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml