name: phpunit

on: [push]

env:
  XDEBUG_MODE: coverage
  PHP_VERSION: 8.2

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Composer
        run: |
          docker run --rm --interactive --tty --volume $container_workdir:/app composer/composer
