name: phpunit

on: [push]

env:
  XDEBUG_MODE: coverage
  PHP_VERSION: 8.2

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v6

      - name: Run Composer
        run: |
          docker run --rm --interactive --volume $GITHUB_WORKSPACE:/app composer/composer dump-autoload
      
      - name: Run PHPUnit
        run: |
          docker run --rm --interactive -p 8081:80 --expose 80 --tty --volume $PWD:/app -w /app pvillareal/php:8.3-cli php ./vendor/bin/phpunit
          
          
